version: "3"
services:
  gibbon:
    build:
      context: .
    container_name: gibbon
    environment:
      GIBBON_AUTOINSTALL: 0
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      GIBBON_USERNAME: ${GIBBON_USERNAME}
      GIBBON_PASSWORD: ${GIBBON_PASSWORD}
      GIBBON_EMAIL: efeariaroo@gmail.com
      GIBBON_URL: ${GIBBON_URL}
      GIBBON_SYSTEM_NAME: Gibbon_EfeAriaroo
      GIBBON_INSTALL_TYPE: Production
      GIBBON_TIMEZONE: Africa/Lagos
      GIBBON_COUNTRY: Nigeria
      GIBBON_CURRENCY: NGN
      GIBBON_ORGANISATION_NAME: WINEPPES PRIVATE SCHOOL
      GIBBON_ORGANISATION_INITIALS: W.E.P.S
    ports:
      - 80:80
